name: Code Quality Checks

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  code-quality:
    uses: brightnucleus/.github/.github/workflows/reusable-code-quality.yml@main
