name: Testing

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron:  '17 1 * * *' # Run every day on a seemly random time.

jobs:
  test:
    uses: brightnucleus/.github/.github/workflows/reusable-testing.yml@main
    with:
        minimum-php: '5.6'
